
[window]
title = "Maarkov"
decorations = "none"
blur = false
opacity = 0.7
padding.x = 0
padding.y = 0

[window.dimensions]
columns = 160
lines = 80

[cursor.style]
shape= "Beam"
blinking = "Never"

[colors]
#transparent_background_colors = true
draw_bold_text_with_bright_colors = true

[env]
TERM = "xterm-256color"

[font]
#glyph_offset = { x = 1, y = 0 }
normal.family = "ShureTechMono Nerd Font"
normal.style = "Regular"
size = 14.0

[font.bold]
family = "ShureTechMono Nerd Font"
style = "Bold"

[font.italic]
family = "ShureTechMono Nerd Font"
style = "Italic"

[general]
live_config_reload = true
working_directory = "None"

# Themes --
import = [ 
  # -- Themes --
  #"~/.config/alacritty/catppuccin-macchiato.toml", 
  "~/.config/alacritty/rosepine.toml", 
  # "~/.config/alacritty/xcad.toml",
  # "~/.config/alacritty/dracula.toml",
  # "~/.config/alacritty/catppuccin-mocha.toml",
  # "~/.config/alacritty/solarized_dark.toml",
  # "~/.config/alacritty/solarized-osaka.toml",
]
