#!/bin/sh

# Single date invocation
set -- $(date '+%I %a %d %I:%M%p')

hour=${1#0}   # remove leading zero (01 → 1)
day=$2
date_num=$3
time=$4

case "$hour" in
	1|13) icon="󱑋" ;;
	2|14) icon="󱑌" ;;
	3|15) icon="󱑍" ;;
	4|16) icon="󱑎" ;;
	5|17) icon="󱑏" ;;
	6|18) icon="󱑐" ;;
	7|19) icon="󱑑" ;;
	8|20) icon="󱑒" ;;
	9|21) icon="󱑓" ;;
	10|22) icon="󱑔" ;;
	11|23) icon="󱑕" ;;
	12|0)  icon="󱑖" ;;
esac

echo "[$day $date_num $icon $time]"
